name: Core-Pipeline
on:
  push:
    branches:
      - main
      - develop
      - "hotfix/**"
      - "feature/**"
  pull_request:

jobs:
  test:
    name: lint & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Run build to resolve dependencies
        run: pnpm build
      - name: Lint & Fix
        run: pnpm lint:fix
      - name: Test
        run: pnpm test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Commit Diff
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto fix lint errors"
          commit_options: "--no-verify"
  pusblish-dry:
    name: Build & dry run on publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: pnpm ci
      - name: Build && publint
        run: pnpm run prepublishOnly
      - name: Publish Dry Run
        run: pnpm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
