name: Core-Pipeline
on: 
  push:
    branches:
      - master
      - develop
      - 'hotfix/**'
      - 'feature/**'
  pull_request: 

jobs:
  test:
    name: lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install
        run: npm ci     
      - name: Lint & Fix
        run: npm run lint:fix
      - name: Test
        run: npm run test:ci
      - name: Commit Diff
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto fix lint errors"
          commit_options: "--no-verify"
  pusblish-dry:
    name: Build & dry run on publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Build && publint
        run: npm run prepublishOnly
      - name: Publish Dry Run
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}