name: Test & Publish
on: [push, pull_request]

jobs:
  test:
    name: lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install
        run: bun install     
      - name: Lint & Fix
        run: bun run lint:fix
      - name: Test
        run: bun test --coverage
      - name: Commit Diff
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto fix lint errors"
          commit_options: "--no-verify"
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build
        run: bun ./build.ts
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node for npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Login
        run: npm login --scope=@cotton-coding
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    name: Publish
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build
        run: bun ./build.ts
      - name: Setup Node for npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}